spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuanke?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081