spring:
  datasource:
    url: jdbc:mysql://110.40.172.88:3306/xuanke?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Admin123!
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081